"""empty message

Revision ID: c551adf7c5f6
Revises: ed657e16ce20
Create Date: 2018-06-24 06:26:30.162053

"""

# revision identifiers, used by Alembic.
revision = 'c551adf7c5f6'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
